name: edu_app
description: A minimal cross-platform Flutter app (Hello World) with light/dark theme support.
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^6.5.1
  confetti: ^0.8.0
  connectivity_plus: ^7.0.0
  file_picker: ^10.3.7
  floating: ^6.0.0
  flutter:
    sdk: flutter
  http: ^0.13.6
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  video_player: ^2.5.1
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
